version: '3'

services:
  nginx:
    build:
      context: ..
      dockerfile: ./deployment/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
  web:
    build:
      context: ..
      dockerfile: ./deployment/web/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8001:8001
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin4.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pg_admin:/var/lib/pgadmin4
  postgres:
    image: postgres:9.6
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  pg_data: {}
  pg_backups: {}
  pg_admin: {}