version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: ./deployment/web/Dockerfile
    #volumes:
    #  - ./app/:/app/
    ports:
      - 8001:8001
      - 8080:8080
  nginx:
    build:
      context: ..
      dockerfile: ./deployment/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - 5000:80