version: '3'

services:
  certbot:
    image: certbot/certbot
    #restart: unless-stopped
    volumes:
      - ./certbot/data/certbot/conf:/etc/letsencrypt
      - ./certbot/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    image: nginx:1.15-alpine
    build:
      context: ..
      dockerfile: ./deployment/nginx/Dockerfile
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/data/certbot/conf:/etc/letsencrypt
      - ./certbot/data/certbot/www:/var/www/certbot
    depends_on:
      - web
    ports:
      - 80:80
      - "443:443"
  web:
    build:
      context: ..
      dockerfile: ./deployment/web/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8001:8001
    environment:
      - DJANGO_SECRET
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    volumes:
      - "${VOLUME_MOUNT}/pg_admin:/var/lib/pgadmin4"
  postgres:
    image: postgres:9.6
    expose:
      - 5432
    volumes:
      - "${VOLUME_MOUNT}/pg_data:/var/lib/postgresql/data"
      - "${VOLUME_MOUNT}/pg_backups:/pg_backups"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
#volumes:
#  pg_data: {}
#  pg_backups: {}
#  pg_admin: {}