# Generated by Django 2.2.6 on 2019-11-30 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('shortened_url', models.TextField(max_length=10, unique=True)),
                ('stats_key', models.TextField(max_length=10, null=True, unique=True)),
                ('original_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(null=True)),
                ('referrer_url', models.URLField(null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickshort.ShortenedUrl')),
            ],
        ),
    ]
