# Generated by Django 2.2.6 on 2019-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='id',
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='shortened_url',
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
