# Generated by Django 2.2.6 on 2019-11-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshort', '0003_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='stats_key',
            field=models.TextField(default='hello', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
