# Generated by Django 2.2.6 on 2019-11-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshort', '0006_auto_20191117_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='source_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
